(node:*) Error: This was rejected
    at * (*test*message*unhandled_promise_trace_warnings.js:*)
    at *
    at *
    at *
    at *
    at *
    at *
    at *
    at *
    at *
(node:*) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
    at getAsynchronousRejectionWarningObject (internal/process/promises.js:*)
    at rejectionHandled (internal/process/promises.js:*)
    at *
    at Promise.then *
    at Promise.catch *
    at Immediate.setImmediate (*test*message*unhandled_promise_trace_warnings.js:*)
    at *
    at *
    at *
